### ISSUE TITLE
Mover los estilos fijos del HTML a la hoja de estilo.

### ISSUE THREAD

**Issue by airvzxf** [JossValladolid/boton-panico-web#8]
Mover los estilos fijos del HTML a la hoja de estilo.

https://github.com/JossValladolid/boton-panico-web/blob/340ec7020ab829e001796458d8fc01e6629bf495/src/index.html#L13

https://github.com/JossValladolid/boton-panico-web/blob/340ec7020ab829e001796458d8fc01e6629bf495/src/index.html#L22

https://github.com/JossValladolid/boton-panico-web/blob/340ec7020ab829e001796458d8fc01e6629bf495/src/index.html#L26

En la hoja de estilos `src/style.css` hay que agregar los estilos del HTML y posteriormente removerlos del mismo.

```css
#errorCodigo, #errorDescripcion {
    color: #800000;
}
 
#exitoEnvio {
    color: #3957a5;
}
```
